'use server';

/**
 * Email Notification Service
 * 
 * Sends email notifications for security alerts and important events.
 */

export interface EmailNotification {
    to: string;
    subject: string;
    body: string;
    html?: string;
}

/**
 * Send security alert email notification
 */
export async function sendSecurityAlertEmail(
    userEmail: string,
    alertType: string,
    severity: string,
    message: string,
    apiKeyName?: string
): Promise<{ success: boolean; message: string }> {
    try {
        // In production, integrate with email service (SendGrid, AWS SES, Resend, etc.)
        // For now, log the notification
        
        const subject = `🔐 Security Alert: ${alertType.replace(/_/g, ' ')}`;
        const body = `
Security Alert Detected

Severity: ${severity.toUpperCase()}
Alert Type: ${alertType.replace(/_/g, ' ')}
${apiKeyName ? `API Key: ${apiKeyName}` : ''}

Details:
${message}

This alert was automatically generated by OfferAnalyst's security monitoring system.

Action Required:
1. Review your API key usage in the dashboard
2. Check for any suspicious activity
3. Update your security settings if necessary

View your security alerts: ${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/dashboard/api-keys

If you did not authorize this activity, please immediately:
- Change your API keys
- Review your account security
- Contact support

---
OfferAnalyst Security Team
        `.trim();

        const html = `
<!DOCTYPE html>
<html>
<head>
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 30px; text-align: center; border-radius: 8px 8px 0 0; }
        .content { background: #f9f9f9; padding: 30px; border-radius: 0 0 8px 8px; }
        .alert-box { background: ${getSeverityColor(severity)}; color: white; padding: 15px; border-radius: 6px; margin: 20px 0; }
        .button { display: inline-block; background: #667eea; color: white; padding: 12px 24px; text-decoration: none; border-radius: 6px; margin-top: 20px; }
        .footer { text-align: center; margin-top: 30px; color: #666; font-size: 12px; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔐 Security Alert</h1>
        </div>
        <div class="content">
            <h2>${alertType.replace(/_/g, ' ')}</h2>
            
            <div class="alert-box">
                <strong>Severity:</strong> ${severity.toUpperCase()}<br>
                ${apiKeyName ? `<strong>API Key:</strong> ${apiKeyName}<br>` : ''}
                <strong>Alert Type:</strong> ${alertType.replace(/_/g, ' ')}
            </div>

            <h3>Details:</h3>
            <p>${message}</p>

            <h3>What to do:</h3>
            <ol>
                <li>Review your API key usage in the dashboard</li>
                <li>Check for any suspicious activity</li>
                <li>Update your security settings if necessary</li>
            </ol>

            <a href="${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/dashboard/api-keys" class="button">
                View Security Alerts
            </a>

            <div style="margin-top: 30px; padding: 15px; background: #fff3cd; border-left: 4px solid #ffc107; border-radius: 4px;">
                <strong>⚠️ If you did not authorize this activity:</strong><br>
                • Change your API keys immediately<br>
                • Review your account security<br>
                • Contact support
            </div>
        </div>
        <div class="footer">
            <p>This alert was automatically generated by OfferAnalyst's security monitoring system.</p>
            <p>© ${new Date().getFullYear()} OfferAnalyst. All rights reserved.</p>
        </div>
    </div>
</body>
</html>
        `.trim();

        // TODO: Integrate with actual email service
        // Example with Resend:
        // import { Resend } from 'resend';
        // const resend = new Resend(process.env.RESEND_API_KEY);
        // await resend.emails.send({
        //     from: 'security@offeranalyst.com',
        //     to: userEmail,
        //     subject,
        //     html
        // });

        if (process.env.NODE_ENV === 'development') {
            console.log('📧 [Email Notification]');
            console.log('To:', userEmail);
            console.log('Subject:', subject);
            console.log('Body:', body);
        }

        return {
            success: true,
            message: 'Email notification sent successfully'
        };
    } catch (error) {
        console.error('Error sending email notification:', error);
        return {
            success: false,
            message: 'Failed to send email notification'
        };
    }
}

/**
 * Send key rotation reminder email
 */
export async function sendKeyRotationReminderEmail(
    userEmail: string,
    apiKeyName: string,
    daysSinceCreation: number
): Promise<{ success: boolean; message: string }> {
    try {
        const subject = '🔄 API Key Rotation Reminder';
        const body = `
Time to Rotate Your API Key

Your API key "${apiKeyName}" has been active for ${daysSinceCreation} days.

For security best practices, we recommend rotating API keys every 90 days.

How to rotate:
1. Go to your API Keys dashboard
2. Add a new API key for the same provider
3. Update your services to use the new key
4. Delete the old key

View your API keys: ${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/dashboard/api-keys

---
OfferAnalyst Security Team
        `.trim();

        if (process.env.NODE_ENV === 'development') {
            console.log('📧 [Key Rotation Reminder]');
            console.log('To:', userEmail);
            console.log('Subject:', subject);
            console.log('Body:', body);
        }

        return {
            success: true,
            message: 'Rotation reminder sent successfully'
        };
    } catch (error) {
        console.error('Error sending rotation reminder:', error);
        return {
            success: false,
            message: 'Failed to send rotation reminder'
        };
    }
}

/**
 * Send key expiration warning email
 */
export async function sendKeyExpirationWarningEmail(
    userEmail: string,
    apiKeyName: string,
    daysUntilExpiration: number
): Promise<{ success: boolean; message: string }> {
    try {
        const subject = '⏰ API Key Expiring Soon';
        const body = `
Your API Key Will Expire Soon

Your API key "${apiKeyName}" will expire in ${daysUntilExpiration} days.

To avoid service interruption:
1. Create a new API key before expiration
2. Update your services
3. Consider extending the expiration date

Manage your keys: ${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'}/dashboard/api-keys

---
OfferAnalyst Team
        `.trim();

        if (process.env.NODE_ENV === 'development') {
            console.log('📧 [Key Expiration Warning]');
            console.log('To:', userEmail);
            console.log('Subject:', subject);
            console.log('Body:', body);
        }

        return {
            success: true,
            message: 'Expiration warning sent successfully'
        };
    } catch (error) {
        console.error('Error sending expiration warning:', error);
        return {
            success: false,
            message: 'Failed to send expiration warning'
        };
    }
}

function getSeverityColor(severity: string): string {
    switch (severity) {
        case 'critical':
            return '#dc2626';
        case 'high':
            return '#ea580c';
        case 'medium':
            return '#ca8a04';
        case 'low':
            return '#2563eb';
        default:
            return '#6b7280';
    }
}
